backend/controllers/HotelController.php
<?php

namespace backend\controllers;

use app\models\hotel\HotelHasService;
use app\models\hotel\HotelTaxonomyService;
use app\models\media\Media;
use Yii;
use app\models\hotel\Hotel;
use app\models\hotel\HotelRoom;
use app\models\hotel\HotelSearch;
use app\models\Model;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;


/**
 * HotelController implements the CRUD actions for Hotel model.
 */
class HotelController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Hotel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new HotelSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Hotel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Hotel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Hotel;
        $model_room = new HotelRoom();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model'      => $model,
                'model_room' => $model_room,
            ]);
        }
    }


    public function actionCreateroom()
    {
        $model = new HotelRoom;


        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate() && $model->save()) {
                if (Yii::$app->request->isAjax) {

                    $model_hotel = $this->findModel($model->hotel_id);

                    $rooms_table = $this->renderAjax('partials/_rooms_table', [
                        'model' => $model_hotel,
                    ]);

                    Yii::$app->response->format = Response::FORMAT_JSON;

                    return [
                        'success' => true,
                        'data'    => [
                            'refresh' => $rooms_table
                        ]
                    ];
                }

                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;

                    return [
                        'error'  => true,
                        'errors' => $model->getErrors()
                    ];
                }
            }
        }
    }

    /**
     * Updates an existing Hotel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model_room = new HotelRoom();
        $media = new Media();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model'      => $model,
                'model_room' => $model_room,
                'media'      => $media,

            ]);
        }
    }

    /**
     * Deletes an existing Hotel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionHotelroomdelete($id)
    {
        $model = $this->findModelHotelRoom($id);

        $hotel_id=$model->hotel_id;

        $model->delete();

        return $this->redirect(['hotel/update',
            'id' => $hotel_id
        ]);

    }

    /**
     * Deletes an existing Hotel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Hotel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Hotel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelHotelRoom($id)
    {
        if (($model = HotelRoom::findOne($id)) !== null) {


            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Finds the Hotel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Hotel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Hotel::findOne($id)) !== null) {

            $model->services = $model->getServicesAsArray();

            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/hotel/partials/_gallery_form.php
<?php
use app\models\media\Media;
use dosamigos\fileupload\FileUploadUI;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;


?>

<span class="m-section__sub">
<button type="button" class="btn btn-success" data-toggle="modal"
        data-target="#galeria_imagenes_<?php echo $room->id ?>">
Galería de Imagenes
</button>
</span>

<div class="modal fade" id="galeria_imagenes_<?php echo $room->id ?>" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Galería Imagenes
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <?php foreach ($room->getGallery() as $image): ?>
                        <div class="col-md-2">
                            <?php echo Html::img(Yii::$app->params['URL_FRONT_PUBLIC_FILES_THUMBS'] . '100x100_' . $image->uri) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php $form_gallery = ActiveForm::begin(['options' => [
                    'enctype' => 'multipart/form-data',
                    'id'      => 'galeria_imagenes_' . $room->id
                ]]);
                ?>
                <div class="form-group">
                    <?php
                    echo FileUploadUI::widget([
                        'model'         => new Media(),
                        'attribute'     => 'image['. $room->id.']',
                        'url'           => Url::to(['media/imageupload/', 'type' => 'HOTEL_ROOM', 'id' => $room->id]),
                        'gallery'       => false,
                        'fieldOptions'  => [
                            'accept' => 'image/*'
                        ],
                        'clientOptions' => [
                            'maxFileSize' => 2000000
                        ],
                        'clientEvents'  => [
                            'fileuploaddone' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
                            'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
                        ],
                    ]); ?>
                </div>
            </div>


            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

backend/views/hotel/partials/_new_room.php
<?php
use demogorgorn\ajax\AjaxSubmitButton;
use dosamigos\fileupload\FileUploadUI;
use yii\widgets\ActiveForm;
use yii\helpers\Html;


?>

<span class="m-section__sub">
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#nueva_habitacion">
Agregar nueva habitación
</button>
               </span>

<div class="modal fade" id="nueva_habitacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Nueva Habitación
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">
												&times;
											</span>
                </button>
            </div>
            <div class="modal-body">


                <?php $form_add_room = ActiveForm::begin(['options' => [
                    'enctype' => 'multipart/form-data',
                    'id'      => 'add-room'
                ]]); ?>


                <?= $form_add_room->field($model_room, 'hotel_id')->hiddenInput(['value' => $model->id])->label(false); ?>

                <?= $form_add_room->field($model_room, 'title')->textInput(['maxlength' => true]) ?>

                <?= $form_add_room->field($model_room, 'description')->textarea() ?>


            </div>
            <div class="modal-footer">

                <div class="form-group">
                    <?php
                    AjaxSubmitButton::begin([
                        'label'             => 'Crear Nueva Habitación',
                        'useWithActiveForm' => 'add-room',

                        'ajaxOptions' => [
                            'type'    => 'POST',
                            'url'     => '/hotel/createroom',
                            'success' => new \yii\web\JsExpression("function(result) {
                            console.log(result);
                            $('#room_table').html(result.data.refresh);
                                                        
            }"),
                        ],
                        'options'     => ['class' => 'btn btn-success', 'type' => 'submit', 'id' => 'add-button'],
                    ]);
                    AjaxSubmitButton::end();

                    ?>
                </div>
            </div>


            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

backend/views/hotel/partials/_rooms_table.php
<?php use app\models\hotel\HotelRoomSchedule;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

if ($model->hotelRooms): ?>

    <div class="m-section__content">
        <table class="table">
            <thead>
            <tr>

                <th>Título</th>
                <th>Galeria de Imagenes</th>
                <th>Horarios</th>
                <th>Servicios</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($model->hotelRooms as $room): ?>
                <tr>
                    <td><?php echo $room->title ?></td>
                    <td>
                        <?php
                        echo $this->render('_gallery_form', [
                            'room' => $room,

                        ]);
                        ?>
                    </td>
                    <td>
                        <?php
                            echo $this->render('//hotelroomschedule/_form_create', [
                                'room' => $room,


                            ]);
                            ?>

                    </td>
                    <td>
                        <?php
                        echo $this->render('//hotelroomservice/_form_create', [
                            'room' => $room,



                        ]);
                        ?>
                    </td>
                    <td>
                        <button type="button" class="btn btn-info">
                            Ver Detalle
                        </button>
                        <a href="/hotel/hotelroomdelete/<?php echo $room->id?>" class="btn btn-danger" data-pjax="0"
                           data-confirm="¿ Estás seguro que deseas borrar el item <?php echo $room->title?> ?"
                           data-method="post">Eliminar</a>

                    </td>
                </tr>
            <?php endforeach; ?>


            </tbody>
        </table>
    </div>
<?php endif; ?>